### ISSUE TITLE
Make portal top bar legible

### ISSUE THREAD

**Issue by iannesbitt** [NCEAS/metacatui-themes#11]
Currently, the top bar in portals is a light grey that does not fit with the theme and makes the top bar text nearly impossible to read. The theme colors should be set in `config.js` but this particular color is set in the theme's `metacatui.css`.

How it currently looks:
![image](https://github.com/NCEAS/metacatui-themes/assets/18689918/aa719e3f-e4b7-4eea-a7bb-b0207ab5e246)

How it should look:
![image](https://github.com/NCEAS/metacatui-themes/assets/18689918/ab0aed2f-1400-4db4-8607-7f7c250d2e81)

**Comment by iannesbitt** [comment]
Theme colors are set in `config.js`, stored as CSS variables in `portal.html` and then applied in the CSS documents:

```html
  <style type="text/css">
    :root {
      --portal-primary-color: <%=primaryColor%>;
      --portal-secondary-color: <%=secondaryColor%>;
      --portal-accent-color: <%=accentColor%>;
      --portal-primary-color-transparent: <%=primaryColorTransparent%>;
      --portal-secondary-color-transparent: <%=secondaryColorTransparent%>;
      --portal-accent-color-transparent: <%=accentColorTransparent%>;

    }
  </style>
```

So I changed the portal background color to follow the theme in `metacatui.css`:
```css
.Portal.Editor #Navbar, .PortalView #Navbar, .Portal.Editor .navbar-inner, .PortalView .navbar-inner {
    /* ... */
    background-color: var(--portal-primary-color);
}
```
